[build]
  command = "npm run build"
  publish = "build"
  functions = "build"
[functions]
external_node_modules = [
    name = "server"
    script = "build/server.js"
  ]
  

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
