[build]
  command = "npm run build"
  publish = "build"
[[functions]]
  name = "server"
  script = "build/server.js"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
